# Generated by Django 5.0.7 on 2024-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
