# Generated by Django 5.0.7 on 2024-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tan_Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(help_text='Discount value percentage', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_redemptions',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
