# Generated by Django 5.0.7 on 2024-10-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tan_Hotel', '0003_bill_points_used_loyaltypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='points_used',
        ),
        migrations.DeleteModel(
            name='LoyaltyPoint',
        ),
    ]
